Repository ssitvit/Code-Canvas, pull requests merged in 2023-08, with the labels that each got.

#527 Temperature converter[GSSOC'23]
  index.html
  projects/Temperature Converter/README.md
  projects/Temperature Converter/Temperature Converter.png
  projects/Temperature Converter/contributing.md
  projects/Temperature Converter/contributors.md
  projects/Temperature Converter/index.html
  projects/Temperature Converter/main.js
  projects/Temperature Converter/style.css
Labels: gssoc23, level2

#531 Added space themed website
  index.html
  projects/Astromania/Thank-styles.css
  projects/Astromania/Thank-you.html
  projects/Astromania/assets/ai-tech.svg
  projects/Astromania/assets/black-hole.svg
  projects/Astromania/assets/download.jpg
  projects/Astromania/assets/earth-1756274_1280.webp
  projects/Astromania/assets/favicon.svg
  projects/Astromania/assets/mainpage.png
  projects/Astromania/assets/nebulea.svg
  projects/Astromania/assets/resources/download (1).jpg
  projects/Astromania/assets/resources/download (2).jpg
  projects/Astromania/assets/resources/download (3).jpg
  projects/Astromania/assets/resources/download (4).jpg
  projects/Astromania/assets/resources/download.jpg
  projects/Astromania/assets/resources/images.jpg
  projects/Astromania/assets/rock.svg
  projects/Astromania/assets/space-scene.svg
  projects/Astromania/assets/spaceel.svg
  projects/Astromania/assets/spacehd.jpg
  projects/Astromania/index.html
  projects/Astromania/styles.css
Labels: gssoc23

#543 Added Netflix-Clone
  assets/style.css
  index.html
  projects/Netflix-Replica/LICENSE
  projects/Netflix-Replica/README.md
  projects/Netflix-Replica/css/style.css
  projects/Netflix-Replica/image/background.jpg
  projects/Netflix-Replica/image/background1.jpg
  projects/Netflix-Replica/image/boxshot.png
  projects/Netflix-Replica/image/device-pile-in.png
  projects/Netflix-Replica/image/img-1
  projects/Netflix-Replica/image/logo.png
  projects/Netflix-Replica/image/mobile.jpg
  projects/Netflix-Replica/image/other_icons/globe.png
  projects/Netflix-Replica/image/other_icons/plus.png
  projects/Netflix-Replica/image/other_icons/plus.svg
  projects/Netflix-Replica/image/other_icons/tick.png
  projects/Netflix-Replica/image/pngwing.com(3).png
  projects/Netflix-Replica/image/show_pic/p1.png
  projects/Netflix-Replica/image/show_pic/p10.png
  projects/Netflix-Replica/image/show_pic/p11.png
  projects/Netflix-Replica/image/show_pic/p12.png
  projects/Netflix-Replica/image/show_pic/p2.png
  projects/Netflix-Replica/image/show_pic/p3.png
  projects/Netflix-Replica/image/show_pic/p4.png
  projects/Netflix-Replica/image/show_pic/p5.png
  projects/Netflix-Replica/image/show_pic/p6.png
  projects/Netflix-Replica/image/show_pic/p7.png
  projects/Netflix-Replica/image/show_pic/p8.png
  projects/Netflix-Replica/image/show_pic/p9.png
  projects/Netflix-Replica/image/show_pic/shows.svg
  projects/Netflix-Replica/image/tv.png
  projects/Netflix-Replica/image/video-devices-in.m4v
  projects/Netflix-Replica/image/video-tv-in-0819.m4v
  projects/Netflix-Replica/index.html
Labels: gssoc23, level2

#407 feat: Add GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/Pull_Request_Template.md
  .github/workflows/dependabot.yml
Labels: good first issue, gssoc23, level1

#448 [GSSoC'23] Dots-Boxes Game Completed
  index.html
  projects/Dots-and-Boxes-Game/Dots-and-Boxes-Game.png
  projects/Dots-and-Boxes-Game/README.md
  projects/Dots-and-Boxes-Game/favicon.ico
  projects/Dots-and-Boxes-Game/index.html
  projects/Dots-and-Boxes-Game/script.js
  projects/Dots-and-Boxes-Game/sounds/click.mp3
  projects/Dots-and-Boxes-Game/sounds/fill.mp3
  projects/Dots-and-Boxes-Game/sounds/win.mp3
  projects/Dots-and-Boxes-Game/style.css
Labels: gssoc23, level2
