Repository ssitvit/Code-Canvas, pull requests merged in 2023-05, with the labels that each got.

#101 GSSoC'23 | Project Addition Weather Website
  index.html
  projects/Weather_Website/Images/images.jpeg
  projects/Weather_Website/index.html
  projects/Weather_Website/script.js
  projects/Weather_Website/style.css
Labels: good first issue, GSSoC'23

#153 Updated the README.md file
  README.md
  assets/Code-Canvas-1.jpeg
  assets/Code-Canvas-2.jpeg
Labels: GSSoC'23, level1

#191 Created a Rock Paper Scissors Game
  index.html
  projects/Rock_Paper_Scissors/README.md
  projects/Rock_Paper_Scissors/game rock paper scissors.jpg
  projects/Rock_Paper_Scissors/images/paper.png
  projects/Rock_Paper_Scissors/images/rock.png
  projects/Rock_Paper_Scissors/images/scissors.png
  projects/Rock_Paper_Scissors/index.html
  projects/Rock_Paper_Scissors/script.js
  projects/Rock_Paper_Scissors/style.css
Labels: GSSoC'23, level2
