Repository ssitvit/Code-Canvas, pull requests merged in 2023-07, with the labels that each got.

#482 Stopwatch
  index.html
  projects/Stopwatch/Contributing.md
  projects/Stopwatch/Contributors.md
  projects/Stopwatch/README.md
  projects/Stopwatch/Stopwatch.png
  projects/Stopwatch/index.html
  projects/Stopwatch/script.js
  projects/Stopwatch/style.css
Labels: gssoc23, level2

#483 Hotstar_Clone
  index.html
  projects/Hotstar_Clone/Contributing.md
  projects/Hotstar_Clone/Contributors.md
  projects/Hotstar_Clone/Hotstar.png
  projects/Hotstar_Clone/images/add.png
  projects/Hotstar_Clone/images/disney.PNG
  projects/Hotstar_Clone/images/geographic.PNG
  projects/Hotstar_Clone/images/logo.png
  projects/Hotstar_Clone/images/marvel.PNG
  projects/Hotstar_Clone/images/nxt.png
  projects/Hotstar_Clone/images/pixar.PNG
  projects/Hotstar_Clone/images/play.png
  projects/Hotstar_Clone/images/poster 1.png
  projects/Hotstar_Clone/images/poster 10.png
  projects/Hotstar_Clone/images/poster 11.png
  projects/Hotstar_Clone/images/poster 12.png
  projects/Hotstar_Clone/images/poster 2.png
  projects/Hotstar_Clone/images/poster 3.png
  projects/Hotstar_Clone/images/poster 4.png
  projects/Hotstar_Clone/images/poster 5.png
  projects/Hotstar_Clone/images/poster 6.png
  projects/Hotstar_Clone/images/poster 7.png
  projects/Hotstar_Clone/images/poster 8.png
  projects/Hotstar_Clone/images/poster 9.png
  projects/Hotstar_Clone/images/pre.png
  projects/Hotstar_Clone/images/slider 1.PNG
  projects/Hotstar_Clone/images/slider 2.PNG
  projects/Hotstar_Clone/images/slider 3.PNG
  projects/Hotstar_Clone/images/slider 4.PNG
  projects/Hotstar_Clone/images/slider 5.PNG
  projects/Hotstar_Clone/images/star-wars.PNG
  projects/Hotstar_Clone/index.html
  projects/Hotstar_Clone/index.js
  projects/Hotstar_Clone/styles.css
  projects/Hotstar_Clone/videos/disney.mp4
  projects/Hotstar_Clone/videos/geographic.mp4
  projects/Hotstar_Clone/videos/marvel.mp4
  projects/Hotstar_Clone/videos/pixar.mp4
  projects/Hotstar_Clone/videos/star-war.mp4
Labels: gssoc23

#481 Added Job Application Form
  .vscode/settings.json
  index.html
  projects/A_Tribute_Page/index.html
  projects/A_Tribute_Page/main.png
  projects/A_Tribute_Page/stephen-hawking.jpg
  projects/A_Tribute_Page/style.css
  projects/Job_Application_Form/frontpage.png
  projects/Job_Application_Form/index.html
  projects/Job_Application_Form/style.css
Labels: gssoc23, level2

#477 Flappy Bird Game Added
  index.html
  projects/Flappy_Bird_Game/images/All_In_One_image.png
  projects/Flappy_Bird_Game/images/flappy-bird-img.jpg
  projects/Flappy_Bird_Game/index.html
  projects/Flappy_Bird_Game/script.js
  projects/Flappy_Bird_Game/style.css
Labels: gssoc23, level3

#485 Web Animation
  index.html
  projects/Web Animation/Contributing.md
  projects/Web Animation/Contributors.md
  projects/Web Animation/README.md
  projects/Web Animation/Web Animation.png
  projects/Web Animation/index.css
  projects/Web Animation/index.html
Labels: gssoc23, level1
